# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 675d80578921dc74f74d98f8b0a2ecf86a5abf7fab09678b98aef9da2a02c0318ecb5408a284322770dddf9c82ec9a4bd17ab6e557eb8a0624c6e6a93c2aa31a

test:
  secret_key_base: 2b8f5d6055ef9c4614f8a8013b56932976058fb214799c0aee427e2c9f192768d9ff33467fd7be5c1cd38b5d21a2459ab962c285ade3716f77c189222ebd6c77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
